/* The following code was generated by JFlex 1.3.5 on 4/10/18 12:18 PM */

package stl.block;

import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;

import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 4/10/18 12:18 PM from the specification file
 * <tt>file:/home/redsky/workspace/TDL/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\13\1\3\1\2\1\0\1\3\1\1\16\13\4\0\1\3\1\21"+
    "\1\7\1\0\1\12\1\27\1\31\1\11\1\32\1\33\1\6\1\25"+
    "\1\15\1\26\1\16\1\5\12\4\1\17\1\14\1\23\1\22\1\24"+
    "\1\20\1\0\22\12\1\60\7\12\1\36\1\10\1\37\1\0\1\12"+
    "\1\0\1\57\1\62\1\40\1\50\1\47\1\51\1\61\1\56\1\55"+
    "\2\12\1\63\1\54\1\42\1\41\1\46\1\12\1\52\1\43\1\44"+
    "\1\53\1\64\1\65\1\12\1\45\1\12\1\34\1\30\1\35\1\0"+
    "\41\13\2\0\4\12\4\0\1\12\2\0\1\13\7\0\1\12\4\0"+
    "\1\12\5\0\27\12\1\0\37\12\1\0\u01ca\12\4\0\14\12\16\0"+
    "\5\12\7\0\1\12\1\0\1\12\21\0\160\13\5\12\1\0\2\12"+
    "\2\0\4\12\10\0\1\12\1\0\3\12\1\0\1\12\1\0\24\12"+
    "\1\0\123\12\1\0\213\12\1\0\5\13\2\0\236\12\11\0\46\12"+
    "\2\0\1\12\7\0\47\12\7\0\1\12\1\0\55\13\1\0\1\13"+
    "\1\0\2\13\1\0\2\13\1\0\1\13\10\0\33\12\5\0\3\12"+
    "\15\0\5\13\6\0\1\12\4\0\13\13\5\0\53\12\37\13\4\0"+
    "\2\12\1\13\143\12\1\0\1\12\10\13\1\0\6\13\2\12\2\13"+
    "\1\0\4\13\2\12\12\13\3\12\2\0\1\12\17\0\1\13\1\12"+
    "\1\13\36\12\33\13\2\0\131\12\13\13\1\12\16\0\12\13\41\12"+
    "\11\13\2\12\4\0\1\12\5\0\26\12\4\13\1\12\11\13\1\12"+
    "\3\13\1\12\5\13\22\0\31\12\3\13\104\0\1\12\1\0\13\12"+
    "\67\0\33\13\1\0\4\13\66\12\3\13\1\12\22\13\1\12\7\13"+
    "\12\12\2\13\2\0\12\13\1\0\7\12\1\0\7\12\1\0\3\13"+
    "\1\0\10\12\2\0\2\12\2\0\26\12\1\0\7\12\1\0\1\12"+
    "\3\0\4\12\2\0\1\13\1\12\7\13\2\0\2\13\2\0\3\13"+
    "\1\12\10\0\1\13\4\0\2\12\1\0\3\12\2\13\2\0\12\13"+
    "\4\12\7\0\1\12\5\0\3\13\1\0\6\12\4\0\2\12\2\0"+
    "\26\12\1\0\7\12\1\0\2\12\1\0\2\12\1\0\2\12\2\0"+
    "\1\13\1\0\5\13\4\0\2\13\2\0\3\13\3\0\1\13\7\0"+
    "\4\12\1\0\1\12\7\0\14\13\3\12\1\13\13\0\3\13\1\0"+
    "\11\12\1\0\3\12\1\0\26\12\1\0\7\12\1\0\2\12\1\0"+
    "\5\12\2\0\1\13\1\12\10\13\1\0\3\13\1\0\3\13\2\0"+
    "\1\12\17\0\2\12\2\13\2\0\12\13\1\0\1\12\17\0\3\13"+
    "\1\0\10\12\2\0\2\12\2\0\26\12\1\0\7\12\1\0\2\12"+
    "\1\0\5\12\2\0\1\13\1\12\7\13\2\0\2\13\2\0\3\13"+
    "\10\0\2\13\4\0\2\12\1\0\3\12\2\13\2\0\12\13\1\0"+
    "\1\12\20\0\1\13\1\12\1\0\6\12\3\0\3\12\1\0\4\12"+
    "\3\0\2\12\1\0\1\12\1\0\2\12\3\0\2\12\3\0\3\12"+
    "\3\0\14\12\4\0\5\13\3\0\3\13\1\0\4\13\2\0\1\12"+
    "\6\0\1\13\16\0\12\13\11\0\1\12\7\0\3\13\1\0\10\12"+
    "\1\0\3\12\1\0\27\12\1\0\12\12\1\0\5\12\3\0\1\12"+
    "\7\13\1\0\3\13\1\0\4\13\7\0\2\13\1\0\2\12\6\0"+
    "\2\12\2\13\2\0\12\13\22\0\2\13\1\0\10\12\1\0\3\12"+
    "\1\0\27\12\1\0\12\12\1\0\5\12\2\0\1\13\1\12\7\13"+
    "\1\0\3\13\1\0\4\13\7\0\2\13\7\0\1\12\1\0\2\12"+
    "\2\13\2\0\12\13\1\0\2\12\17\0\2\13\1\0\10\12\1\0"+
    "\3\12\1\0\51\12\2\0\1\12\7\13\1\0\3\13\1\0\4\13"+
    "\1\12\10\0\1\13\10\0\2\12\2\13\2\0\12\13\12\0\6\12"+
    "\2\0\2\13\1\0\22\12\3\0\30\12\1\0\11\12\1\0\1\12"+
    "\2\0\7\12\3\0\1\13\4\0\6\13\1\0\1\13\1\0\10\13"+
    "\22\0\2\13\15\0\60\12\1\13\2\12\7\13\4\0\10\12\10\13"+
    "\1\0\12\13\47\0\2\12\1\0\1\12\2\0\2\12\1\0\1\12"+
    "\2\0\1\12\6\0\4\12\1\0\7\12\1\0\3\12\1\0\1\12"+
    "\1\0\1\12\2\0\2\12\1\0\4\12\1\13\2\12\6\13\1\0"+
    "\2\13\1\12\2\0\5\12\1\0\1\12\1\0\6\13\2\0\12\13"+
    "\2\0\4\12\40\0\1\12\27\0\2\13\6\0\12\13\13\0\1\13"+
    "\1\0\1\13\1\0\1\13\4\0\2\13\10\12\1\0\44\12\4\0"+
    "\24\13\1\0\2\13\5\12\13\13\1\0\44\13\11\0\1\13\71\0"+
    "\53\12\24\13\1\12\12\13\6\0\6\12\4\13\4\12\3\13\1\12"+
    "\3\13\2\12\7\13\3\12\4\13\15\12\14\13\1\12\17\13\2\0"+
    "\46\12\1\0\1\12\5\0\1\12\2\0\53\12\1\0\u014d\12\1\0"+
    "\4\12\2\0\7\12\1\0\1\12\1\0\4\12\2\0\51\12\1\0"+
    "\4\12\2\0\41\12\1\0\4\12\2\0\7\12\1\0\1\12\1\0"+
    "\4\12\2\0\17\12\1\0\71\12\1\0\4\12\2\0\103\12\2\0"+
    "\3\13\40\0\20\12\20\0\125\12\14\0\u026c\12\2\0\21\12\1\0"+
    "\32\12\5\0\113\12\3\0\3\12\17\0\15\12\1\0\4\12\3\13"+
    "\13\0\22\12\3\13\13\0\22\12\2\13\14\0\15\12\1\0\3\12"+
    "\1\0\2\13\14\0\64\12\40\13\3\0\1\12\3\0\2\12\1\13"+
    "\2\0\12\13\41\0\3\13\2\0\12\13\6\0\130\12\10\0\51\12"+
    "\1\13\1\12\5\0\106\12\12\0\35\12\3\0\14\13\4\0\14\13"+
    "\12\0\12\13\36\12\2\0\5\12\13\0\54\12\4\0\21\13\7\12"+
    "\2\13\6\0\12\13\46\0\27\12\5\13\4\0\65\12\12\13\1\0"+
    "\35\13\2\0\13\13\6\0\12\13\15\0\1\12\130\0\5\13\57\12"+
    "\21\13\7\12\4\0\12\13\21\0\11\13\14\0\3\13\36\12\15\13"+
    "\2\12\12\13\54\12\16\13\14\0\44\12\24\13\10\0\12\13\3\0"+
    "\3\12\12\13\44\12\122\0\3\13\1\0\25\13\4\12\1\13\4\12"+
    "\3\13\2\12\11\0\300\12\47\13\25\0\4\13\u0116\12\2\0\6\12"+
    "\2\0\46\12\2\0\6\12\2\0\10\12\1\0\1\12\1\0\1\12"+
    "\1\0\1\12\1\0\37\12\2\0\65\12\1\0\7\12\1\0\1\12"+
    "\3\0\3\12\1\0\7\12\3\0\4\12\2\0\6\12\4\0\15\12"+
    "\5\0\3\12\1\0\7\12\16\0\5\13\32\0\5\13\20\0\2\12"+
    "\23\0\1\12\13\0\5\13\5\0\6\13\1\0\1\12\15\0\1\12"+
    "\20\0\15\12\3\0\33\12\25\0\15\13\4\0\1\13\3\0\14\13"+
    "\21\0\1\12\4\0\1\12\2\0\12\12\1\0\1\12\3\0\5\12"+
    "\6\0\1\12\1\0\1\12\1\0\1\12\1\0\4\12\1\0\13\12"+
    "\2\0\4\12\5\0\5\12\4\0\1\12\21\0\51\12\u0a77\0\57\12"+
    "\1\0\57\12\1\0\205\12\6\0\4\12\3\13\2\12\14\0\46\12"+
    "\1\0\1\12\5\0\1\12\2\0\70\12\7\0\1\12\17\0\1\13"+
    "\27\12\11\0\7\12\1\0\7\12\1\0\7\12\1\0\7\12\1\0"+
    "\7\12\1\0\7\12\1\0\7\12\1\0\7\12\1\0\40\13\57\0"+
    "\1\12\u01d5\0\3\12\31\0\11\12\6\13\1\0\5\12\2\0\5\12"+
    "\4\0\126\12\2\0\2\13\2\0\3\12\1\0\132\12\1\0\4\12"+
    "\5\0\51\12\3\0\136\12\21\0\33\12\65\0\20\12\u0200\0\u19b6\12"+
    "\112\0\u51cd\12\63\0\u048d\12\103\0\56\12\2\0\u010d\12\3\0\20\12"+
    "\12\13\2\12\24\0\57\12\1\13\4\0\12\13\1\0\31\12\7\0"+
    "\1\13\120\12\2\13\45\0\11\12\2\0\147\12\2\0\4\12\1\0"+
    "\4\12\14\0\13\12\115\0\12\12\1\13\3\12\1\13\4\12\1\13"+
    "\27\12\5\13\20\0\1\12\7\0\64\12\14\0\2\13\62\12\21\13"+
    "\13\0\12\13\6\0\22\13\6\12\3\0\1\12\4\0\12\13\34\12"+
    "\10\13\2\0\27\12\15\13\14\0\35\12\3\0\4\13\57\12\16\13"+
    "\16\0\1\12\12\13\46\0\51\12\16\13\11\0\3\12\1\13\10\12"+
    "\2\13\2\0\12\13\6\0\27\12\3\0\1\12\1\13\4\0\60\12"+
    "\1\13\1\12\3\13\2\12\2\13\5\12\2\13\1\12\1\13\1\12"+
    "\30\0\3\12\2\0\13\12\5\13\2\0\3\12\2\13\12\0\6\12"+
    "\2\0\6\12\2\0\6\12\11\0\7\12\1\0\7\12\221\0\43\12"+
    "\10\13\1\0\2\13\2\0\12\13\6\0\u2ba4\12\14\0\27\12\4\0"+
    "\61\12\u2104\0\u016e\12\2\0\152\12\46\0\7\12\14\0\5\12\5\0"+
    "\1\12\1\13\12\12\1\0\15\12\1\0\5\12\1\0\1\12\1\0"+
    "\2\12\1\0\2\12\1\0\154\12\41\0\u016b\12\22\0\100\12\2\0"+
    "\66\12\50\0\15\12\3\0\20\13\20\0\7\13\14\0\2\12\30\0"+
    "\3\12\31\0\1\12\6\0\5\12\1\0\207\12\2\0\1\13\4\0"+
    "\1\12\13\0\12\13\7\0\32\12\4\0\1\12\1\0\32\12\13\0"+
    "\131\12\3\0\6\12\2\0\6\12\2\0\6\12\2\0\3\12\3\0"+
    "\2\12\3\0\2\12\22\0\3\13\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    54,   108,   162,   108,   216,   270,   108,   324,   378, 
      432,   108,   108,   108,   108,   108,   486,   540,   594,   648, 
      702,   756,   108,   810,   864,   108,   108,   108,   108,   108, 
      108,   918,   972,  1026,  1080,  1134,  1188,  1242,  1296,  1350, 
     1404,  1458,  1512,  1566,  1620,  1674,   324,   108,  1728,  1782, 
     1836,   108,   108,   108,   108,   108,   108,   108,   108,  1890, 
     1944,  1998,  2052,  2106,  2160,  2214,  2268,  2322,  2376,  2430, 
     2484,  2538,  2592,  2646,   432,  2700,  2754,  2808,  2862,  2916, 
      324,   108,  2970,  3024,   432,  3078,   432,  3132,  3186,  3240, 
     3294,  3348,  3402,   432,  3456,  3510,   432,  3564,  3618,  3672, 
     3726,  3780,  3834,   432,  3888,  3942,   432,  3996,   432,   432, 
     4050,  4104,  4158,  4212,   432,  4266,   432,  4320,  4374,  4428, 
      432,   432,  4482,  4536,  4590,   432,  4644,   432,  4698,   432, 
      432,  4752,  4806,   432,   432,  4860,   432
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\13\1\3\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\13\1\41\1\42\1\43\1\13\1\44\1\45\1\13"+
    "\1\46\1\47\2\13\1\50\2\13\1\51\1\13\1\52"+
    "\1\13\1\53\1\54\66\3\70\0\1\5\67\0\1\6"+
    "\66\0\1\55\1\56\57\0\7\57\1\60\1\61\55\57"+
    "\10\62\1\63\55\62\4\0\1\13\5\0\2\13\24\0"+
    "\26\13\22\0\1\64\65\0\1\65\65\0\1\66\65\0"+
    "\1\67\70\0\1\70\66\0\1\71\67\0\1\72\66\0"+
    "\1\73\40\0\1\13\5\0\2\13\24\0\1\13\1\74"+
    "\14\13\1\75\7\13\4\0\1\13\5\0\2\13\24\0"+
    "\7\13\1\76\3\13\1\77\12\13\4\0\1\13\5\0"+
    "\2\13\24\0\2\13\1\100\1\13\1\101\21\13\4\0"+
    "\1\13\5\0\2\13\24\0\5\13\1\102\4\13\1\103"+
    "\13\13\4\0\1\13\5\0\2\13\24\0\12\13\1\104"+
    "\13\13\4\0\1\13\5\0\2\13\24\0\2\13\1\105"+
    "\20\13\1\106\2\13\4\0\1\13\5\0\2\13\24\0"+
    "\3\13\1\107\13\13\1\110\6\13\4\0\1\13\5\0"+
    "\2\13\24\0\7\13\1\111\16\13\4\0\1\13\5\0"+
    "\2\13\24\0\2\13\1\112\6\13\1\113\14\13\4\0"+
    "\1\13\5\0\2\13\24\0\4\13\1\114\21\13\4\0"+
    "\1\13\5\0\2\13\24\0\1\13\1\115\24\13\4\0"+
    "\1\13\5\0\2\13\24\0\1\13\1\116\24\13\4\0"+
    "\1\13\5\0\2\13\24\0\16\13\1\117\7\13\1\55"+
    "\1\4\1\5\63\55\6\56\1\120\57\56\7\57\1\121"+
    "\1\61\55\57\11\0\1\122\64\0\1\62\61\0\1\13"+
    "\5\0\2\13\24\0\2\13\1\123\23\13\4\0\1\13"+
    "\5\0\2\13\24\0\17\13\1\124\6\13\4\0\1\13"+
    "\5\0\2\13\24\0\25\13\1\125\4\0\1\13\5\0"+
    "\2\13\24\0\23\13\1\126\2\13\4\0\1\13\5\0"+
    "\2\13\24\0\10\13\1\127\15\13\4\0\1\13\5\0"+
    "\2\13\24\0\12\13\1\130\13\13\4\0\1\13\5\0"+
    "\2\13\24\0\6\13\1\131\17\13\4\0\1\13\5\0"+
    "\2\13\24\0\13\13\1\132\12\13\4\0\1\13\5\0"+
    "\2\13\24\0\15\13\1\133\10\13\4\0\1\13\5\0"+
    "\2\13\24\0\13\13\1\134\12\13\4\0\1\13\5\0"+
    "\2\13\24\0\3\13\1\135\22\13\4\0\1\13\5\0"+
    "\2\13\24\0\4\13\1\136\21\13\4\0\1\13\5\0"+
    "\2\13\24\0\23\13\1\137\2\13\4\0\1\13\5\0"+
    "\2\13\24\0\4\13\1\140\21\13\4\0\1\13\5\0"+
    "\2\13\24\0\4\13\1\141\21\13\4\0\1\13\5\0"+
    "\2\13\24\0\12\13\1\142\13\13\4\0\1\13\5\0"+
    "\2\13\24\0\1\13\1\143\24\13\4\0\1\13\5\0"+
    "\2\13\24\0\15\13\1\144\10\13\4\0\1\13\5\0"+
    "\2\13\24\0\15\13\1\145\10\13\5\56\1\5\1\120"+
    "\57\56\4\0\1\13\5\0\2\13\24\0\3\13\1\146"+
    "\22\13\4\0\1\13\5\0\2\13\24\0\12\13\1\147"+
    "\13\13\4\0\1\13\5\0\2\13\24\0\23\13\1\150"+
    "\2\13\4\0\1\13\5\0\2\13\24\0\13\13\1\151"+
    "\12\13\4\0\1\13\5\0\2\13\24\0\7\13\1\152"+
    "\16\13\4\0\1\13\5\0\2\13\24\0\7\13\1\153"+
    "\16\13\4\0\1\13\5\0\2\13\24\0\2\13\1\154"+
    "\23\13\4\0\1\13\5\0\2\13\24\0\14\13\1\155"+
    "\11\13\4\0\1\13\5\0\2\13\24\0\7\13\1\156"+
    "\16\13\4\0\1\13\5\0\2\13\24\0\3\13\1\157"+
    "\22\13\4\0\1\13\5\0\2\13\24\0\13\13\1\160"+
    "\12\13\4\0\1\13\5\0\2\13\24\0\15\13\1\161"+
    "\10\13\4\0\1\13\5\0\2\13\24\0\23\13\1\162"+
    "\2\13\4\0\1\13\5\0\2\13\24\0\10\13\1\163"+
    "\15\13\4\0\1\13\5\0\2\13\24\0\23\13\1\164"+
    "\2\13\4\0\1\13\5\0\2\13\24\0\4\13\1\165"+
    "\21\13\4\0\1\13\5\0\2\13\24\0\17\13\1\166"+
    "\6\13\4\0\1\13\5\0\2\13\24\0\1\167\25\13"+
    "\4\0\1\13\5\0\2\13\24\0\10\13\1\170\15\13"+
    "\4\0\1\13\5\0\2\13\24\0\4\13\1\171\21\13"+
    "\4\0\1\13\5\0\2\13\24\0\7\13\1\172\16\13"+
    "\4\0\1\13\5\0\2\13\24\0\12\13\1\173\13\13"+
    "\4\0\1\13\5\0\2\13\24\0\2\13\1\174\23\13"+
    "\4\0\1\13\5\0\2\13\24\0\7\13\1\175\16\13"+
    "\4\0\1\13\5\0\2\13\24\0\7\13\1\176\16\13"+
    "\4\0\1\13\5\0\2\13\24\0\1\177\25\13\4\0"+
    "\1\13\5\0\2\13\24\0\4\13\1\200\21\13\4\0"+
    "\1\13\5\0\2\13\24\0\7\13\1\201\16\13\4\0"+
    "\1\13\5\0\2\13\24\0\2\13\1\202\23\13\4\0"+
    "\1\13\5\0\2\13\24\0\21\13\1\203\4\13\4\0"+
    "\1\13\5\0\2\13\24\0\17\13\1\204\6\13\4\0"+
    "\1\13\5\0\2\13\24\0\4\13\1\205\21\13\4\0"+
    "\1\13\5\0\2\13\24\0\11\13\1\206\14\13\4\0"+
    "\1\13\5\0\2\13\24\0\2\13\1\207\23\13\4\0"+
    "\1\13\5\0\2\13\24\0\7\13\1\210\16\13\4\0"+
    "\1\13\5\0\2\13\24\0\12\13\1\211\13\13";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  9,  1,  1,  1,  9,  9,  9,  9,  9, 
     1,  1,  1,  1,  1,  1,  9,  1,  1,  9,  9,  9,  9,  9,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  9, 
     0,  0,  0,  9,  9,  9,  9,  9,  9,  9,  9,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 
     1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    public Lexer(ComplexSymbolFactory _symbolFactory, java.io.InputStream _inputStream){
		this(_inputStream);
        this.symbolFactory = _symbolFactory;
    }

	public Lexer(ComplexSymbolFactory _symbolFactory, java.io.Reader _reader){
		this(_reader);
        this.symbolFactory = _symbolFactory;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
		return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    		System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    		System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4914];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2252) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 7: 
          {  return symbolFactory.newSymbol("Asterisque", UL_Asterisque);  }
        case 138: break;
        case 130: 
          {  return symbolFactory.newSymbol("Type Chaîne", UL_Type_Chaine);  }
        case 139: break;
        case 108: 
          {  return symbolFactory.newSymbol("Enumération", UL_Enumeration);  }
        case 140: break;
        case 96: 
          {  return symbolFactory.newSymbol("Type Entier", UL_Type_Entier);  }
        case 141: break;
        case 14: 
          {  return symbolFactory.newSymbol("Deux Points", UL_Deux_Points);  }
        case 142: break;
        case 24: 
          {  return symbolFactory.newSymbol("Esperluette", UL_Esperluette);  }
        case 143: break;
        case 52: 
          {  return symbolFactory.newSymbol("Double Egal", UL_Double_Egal);  }
        case 144: break;
        case 55: 
          {  return symbolFactory.newSymbol("Double Plus", UL_Double_Plus);  }
        case 145: break;
        case 3: 
        case 4: 
          {   }
        case 146: break;
        case 5: 
          {  return symbolFactory.newSymbol("Nombre Entier", UL_Nombre_Entier, yytext());  }
        case 147: break;
        case 47: 
        case 80: 
          {  return symbolFactory.newSymbol("Chaine de caractères", UL_Chaine, yytext());  }
        case 148: break;
        case 58: 
          {  return symbolFactory.newSymbol("Double Esperluette", UL_Double_Esperluette);  }
        case 149: break;
        case 109: 
          {  return symbolFactory.newSymbol("Sinon", UL_Sinon);  }
        case 150: break;
        case 21: 
          {  return symbolFactory.newSymbol("Moins", UL_Moins);  }
        case 151: break;
        case 13: 
          {  return symbolFactory.newSymbol("Point", UL_Point);  }
        case 152: break;
        case 103: 
          {  return symbolFactory.newSymbol("Nul", UL_Nul);  }
        case 153: break;
        case 127: 
          {  return symbolFactory.newSymbol("Enregistrement", UL_Enregistrement);  }
        case 154: break;
        case 81: 
          {  return symbolFactory.newSymbol("Caractère", UL_Caractere, yytext());  }
        case 155: break;
        case 136: 
          {  return symbolFactory.newSymbol("Type Caractère", UL_Type_Caractere);  }
        case 156: break;
        case 54: 
          {  return symbolFactory.newSymbol("Supérieur Egal", UL_Superieur_Egal);  }
        case 157: break;
        case 125: 
          {  return symbolFactory.newSymbol("Tant que", UL_Tant_Que);  }
        case 158: break;
        case 120: 
          {  return symbolFactory.newSymbol("Afficher", UL_Afficher);  }
        case 159: break;
        case 116: 
          {  return symbolFactory.newSymbol("Définition Constante", UL_Definition_Constante);  }
        case 160: break;
        case 11: 
          {  return symbolFactory.newSymbol("Point Virgule", UL_Point_Virgule);  }
        case 161: break;
        case 129: 
          {  return symbolFactory.newSymbol("Return", UL_Retour);  }
        case 162: break;
        case 86: 
          {  return symbolFactory.newSymbol("Second", UL_Second);  }
        case 163: break;
        case 114: 
          {  return symbolFactory.newSymbol("Type Vide", UL_Type_Vide);  }
        case 164: break;
        case 19: 
          {  return symbolFactory.newSymbol("Supérieur", UL_Superieur);  }
        case 165: break;
        case 18: 
          {  return symbolFactory.newSymbol("Inférieur", UL_Inferieur);  }
        case 166: break;
        case 22: 
          {  return symbolFactory.newSymbol("Pour Cent", UL_Pour_Cent);  }
        case 167: break;
        case 133: 
          {  return symbolFactory.newSymbol("Définition Type", UL_Definition_Type);  }
        case 168: break;
        case 10: 
        case 31: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 42: 
        case 43: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 82: 
        case 83: 
        case 85: 
        case 87: 
        case 88: 
        case 89: 
        case 90: 
        case 91: 
        case 92: 
        case 94: 
        case 95: 
        case 97: 
        case 98: 
        case 99: 
        case 100: 
        case 101: 
        case 102: 
        case 104: 
        case 105: 
        case 107: 
        case 110: 
        case 111: 
        case 112: 
        case 113: 
        case 115: 
        case 117: 
        case 118: 
        case 119: 
        case 122: 
        case 123: 
        case 124: 
        case 126: 
        case 128: 
        case 131: 
        case 132: 
        case 135: 
          {  return symbolFactory.newSymbol("Identificateur", UL_Identificateur, yytext());  }
        case 169: break;
        case 53: 
          {  return symbolFactory.newSymbol("Inférieur Egal", UL_Inferieur_Egal);  }
        case 170: break;
        case 2: 
        case 8: 
        case 9: 
        case 23: 
          {  emit_warning( "Unrecognized character '" + yytext() + "' -- ignored" );  }
        case 171: break;
        case 25: 
          {  return symbolFactory.newSymbol("Parenthese Ouvrante", UL_Parenthese_Ouvrante);  }
        case 172: break;
        case 26: 
          {  return symbolFactory.newSymbol("Parenthese Fermante", UL_Parenthese_Fermante);  }
        case 173: break;
        case 74: 
          {  return symbolFactory.newSymbol("Si", UL_Si);  }
        case 174: break;
        case 16: 
          {  return symbolFactory.newSymbol("Point d'Exclamation", UL_Point_Exclamation);  }
        case 175: break;
        case 29: 
          {  return symbolFactory.newSymbol("Crochet Ouvrant", UL_Crochet_Ouvrant);  }
        case 176: break;
        case 30: 
          {  return symbolFactory.newSymbol("Crochet Fermant", UL_Crochet_Fermant);  }
        case 177: break;
        case 93: 
          {  return symbolFactory.newSymbol("Premier", UL_Premier);  }
        case 178: break;
        case 84: 
          {  return symbolFactory.newSymbol("Nouveau", UL_Nouveau);  }
        case 179: break;
        case 6: 
          {  return symbolFactory.newSymbol("Oblique", UL_Oblique);  }
        case 180: break;
        case 12: 
          {  return symbolFactory.newSymbol("Virgule", UL_Virgule);  }
        case 181: break;
        case 27: 
          {  return symbolFactory.newSymbol("Accolade Ouvrante", UL_Accolade_Ouvrante);  }
        case 182: break;
        case 28: 
          {  return symbolFactory.newSymbol("Accolade Fermante", UL_Accolade_Fermante);  }
        case 183: break;
        case 51: 
          {  return symbolFactory.newSymbol("Exclamation Egal", UL_Exclamation_Egal);  }
        case 184: break;
        case 134: 
          {  return symbolFactory.newSymbol("Type Booléen", UL_Type_Booleen);  }
        case 185: break;
        case 121: 
          {  return symbolFactory.newSymbol("Faux", UL_Faux);  }
        case 186: break;
        case 106: 
          {  return symbolFactory.newSymbol("Vrai", UL_Vrai);  }
        case 187: break;
        case 20: 
          {  return symbolFactory.newSymbol("Plus", UL_Plus);  }
        case 188: break;
        case 17: 
          {  return symbolFactory.newSymbol("Egal", UL_Egal);  }
        case 189: break;
        case 15: 
          {  return symbolFactory.newSymbol("Point d'Interrogation", UL_Point_Interrogation);  }
        case 190: break;
        case 56: 
          {  return symbolFactory.newSymbol("Double Moins", UL_Double_Moins);  }
        case 191: break;
        case 57: 
          {  return symbolFactory.newSymbol("Double Barre", UL_Double_Barre);  }
        case 192: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
