
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package fr.n7.stl.block;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int UL_Private = 52;
  public static final int UL_Egal = 8;
  public static final int UL_Afficher = 33;
  public static final int UL_Public = 51;
  public static final int UL_Identificateur = 40;
  public static final int UL_Moins = 10;
  public static final int UL_Virgule = 3;
  public static final int UL_Parenthese_Fermante = 18;
  public static final int UL_Exclamation_Egal = 28;
  public static final int UL_Sinon = 30;
  public static final int UL_Superieur_Egal = 26;
  public static final int UL_Double_Barre = 15;
  public static final int UL_Esperluette = 14;
  public static final int UL_Chaine = 41;
  public static final int UL_Point = 4;
  public static final int UL_Final = 53;
  public static final int UL_Pour_Cent = 13;
  public static final int UL_Accolade_Ouvrante = 19;
  public static final int UL_Double_Esperluette = 16;
  public static final int UL_Abstract = 55;
  public static final int UL_Nombre_Entier = 43;
  public static final int UL_Plus = 9;
  public static final int UL_Point_Exclamation = 7;
  public static final int UL_Type_Booleen = 35;
  public static final int UL_Crochet_Fermant = 22;
  public static final int UL_Type_Caractere = 36;
  public static final int UL_Superieur = 24;
  public static final int UL_Oblique = 12;
  public static final int UL_Retour = 34;
  public static final int EOF = 0;
  public static final int UL_Faux = 46;
  public static final int UL_Point_Virgule = 2;
  public static final int error = 1;
  public static final int UL_Parenthese_Ouvrante = 17;
  public static final int UL_Static = 54;
  public static final int UL_Implements = 49;
  public static final int UL_Tant_Que = 31;
  public static final int UL_Inferieur_Egal = 25;
  public static final int UL_Inferieur = 23;
  public static final int UL_Crochet_Ouvrant = 21;
  public static final int UL_Extends = 47;
  public static final int UL_Nul = 44;
  public static final int UL_Double_Egal = 27;
  public static final int UL_Si = 29;
  public static final int UL_Caractere = 42;
  public static final int UL_Vrai = 45;
  public static final int UL_Nouveau = 32;
  public static final int UL_Type_Vide = 39;
  public static final int UL_Point_Interrogation = 6;
  public static final int UL_Deux_Points = 5;
  public static final int UL_Asterisque = 11;
  public static final int UL_Accolade_Fermante = 20;
  public static final int UL_Interface = 50;
  public static final int UL_Class = 48;
  public static final int UL_Type_Entier = 38;
  public static final int UL_Type_Chaine = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UL_Point_Virgule",
  "UL_Virgule",
  "UL_Point",
  "UL_Deux_Points",
  "UL_Point_Interrogation",
  "UL_Point_Exclamation",
  "UL_Egal",
  "UL_Plus",
  "UL_Moins",
  "UL_Asterisque",
  "UL_Oblique",
  "UL_Pour_Cent",
  "UL_Esperluette",
  "UL_Double_Barre",
  "UL_Double_Esperluette",
  "UL_Parenthese_Ouvrante",
  "UL_Parenthese_Fermante",
  "UL_Accolade_Ouvrante",
  "UL_Accolade_Fermante",
  "UL_Crochet_Ouvrant",
  "UL_Crochet_Fermant",
  "UL_Inferieur",
  "UL_Superieur",
  "UL_Inferieur_Egal",
  "UL_Superieur_Egal",
  "UL_Double_Egal",
  "UL_Exclamation_Egal",
  "UL_Si",
  "UL_Sinon",
  "UL_Tant_Que",
  "UL_Nouveau",
  "UL_Afficher",
  "UL_Retour",
  "UL_Type_Booleen",
  "UL_Type_Caractere",
  "UL_Type_Chaine",
  "UL_Type_Entier",
  "UL_Type_Vide",
  "UL_Identificateur",
  "UL_Chaine",
  "UL_Caractere",
  "UL_Nombre_Entier",
  "UL_Nul",
  "UL_Vrai",
  "UL_Faux",
  "UL_Extends",
  "UL_Class",
  "UL_Implements",
  "UL_Interface",
  "UL_Public",
  "UL_Private",
  "UL_Final",
  "UL_Static",
  "UL_Abstract"
  };
}

